"""added logging 

Revision ID: 31b938c0ab0f
Revises: 7c65e5a4761a
Create Date: 2025-05-03 21:45:04.316377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31b938c0ab0f'
down_revision = '7c65e5a4761a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('operation', sa.String(length=10), nullable=True),
    sa.Column('old_data', sa.Text(), nullable=True),
    sa.Column('new_data', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['missing_person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('monitor_persons')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_log')
    # ### end Alembic commands ###
