"""Create missing_persons table

Revision ID: 382a4c5bd305
Revises: 
Create Date: 2024-07-25 07:22:27.413644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382a4c5bd305'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('missing_person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missing_person',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('photo_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('occupation', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_known_location', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contact_info', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='missing_person_pkey')
    )
    # ### end Alembic commands ###
